fix

diff --git a/.github/workflows/deploy-server-with-compose.yml b/.github/workflows/deploy-server-with-compose.yml
--- a/.github/workflows/deploy-server-with-compose.yml
+++ b/.github/workflows/deploy-server-with-compose.yml
@@ -19,7 +19,19 @@ jobs:
           uses: docker/login-action@v1
           with:
             username: ${{secrets.DOCKER_EMAIL}}
-            passowrd: ${{secrets.DOCKER_PASSWORD}}
+            password: ${{secrets.DOCKER_PASSWORD}}
 
         - name: push to dockerhub
           run: docker push pyowoongi/ordersystem:latest
+
+        - name: ec2 ssh login and docker compose update
+          uses: appleboy/ssh-action@master
+          with:
+            host:
+            username: ubuntu
+            key: ${{secrets.EC2_PEMKEY}}
+            script: |
+              if ! type docker > /dev/null ; then
+                sudo snap install docker || echo "docker install failed"
+              fi
+              sudo docker login --username ${{secrets.DOCKER_EMAIL}} --password ${{secrets.DOCKER_PASSWORD}}
